config/routes.rb
Pindd::Application.routes.draw do
  resources :groups

  devise_for :users
  resources :notes do
    member do
      put 'toggle'
    end
  end

  root to: 'notes#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :group

  delegate :users, to: :group

  validates :content, presence: true, length: 1..140

  after_create :send_create_note_text

  def my_note?
    self.group.default_group?
  end

  def send_create_note_text(current_user = nil)
    if current_user && TextNotification.send_texts
      TextNotification.new(message: "Hi, #{current_user.email} added '#{self.content}' to #{self.group.name}",
        group: self.group, created_by: current_user).send_text
    end
  end

  def send_complete_note_text(current_user = nil)
    if current_user && check && TextNotification.send_texts
      TextNotification.new(message: "Hi, #{current_user.email} marked '#{self.content}' in #{self.group.name} as complete",
        group: self.group, created_by: current_user).send_text
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  skip_load_resource only: [:create]

  # GET /notes
  # GET /notes.json
  def index
    if params[:groups]
      groups = current_user.groups.where(id: params[:groups])
      @notes = Note.where(group_id: groups)
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    # respond_to do |format|
      if @note.save
        redirect_to notes_url, notice: 'Note was successfully created.'
        # format.html { redirect_to notes_url, notice: 'Note was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @note }
      else
        render action: "new"
      #   format.html { render action: 'new' }
      #   format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    # respond_to do |format|
      if @note.update(note_params)
        sync_update @note
        redirect_to notes_url, notice: 'Note was successfully updated.' 
        # format.html { redirect_to notes_url, notice: 'Note was successfully updated.' }
        # format.json { head :no_content }
      else
        render action: 'edit'
        # format.html { render action: 'edit' }
        # format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    # end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    redirect_to notes_url 
    # respond_to do |format|
    #   format.html { redirect_to notes_url }
    #   format.json { head :no_content }
    # end
  end

  # PUT /notes/1/toggle
  def toggle
    @note = Note.find(params[:id])
    if @note.update_attributes(:check => params[:check])
      @note.send_complete_note_text(current_user)
      sync_update @note
      render 'toggle'
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:content, :check, :group_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
  def note_color note
    if note.my_note?
      "rgb(255,255,136)"
    else
      note.group.color || "#ADC1D6"
    end
  end

  def font_size note
    if note.content.length < 25
      return "font-size:40px;line-height:45px"
    elsif note.content.length < 55
      return "font-size:32px;line-height:35px"
    elsif note.content.length < 75
      return "font-size:24px;line-height:30px"
    elsif note.content.length < 105
      return "font-size:22px;line-height:25px"
    end
      "font-size:18px;line-height:20px"
  end
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="center">
  <div class="new-postit">

    <div class="field">
      <%= f.label :to %>
      <%= f.select :group_id, current_user.groups.map{ |g| [( g.default_group? ? "myself" : g.name), g.id]} %>
    </div>
    <div class="field">
      <%= f.text_area :content%>
      <br><span class="countdown"></span>
    </div>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/notes/edit.html.erb
<%= render 'form' %>

<div class="center">
	<%= link_to 'Show', @note %> |
	<%= link_to 'Back', notes_path %>
</div>

app/views/notes/index.html.erb
<% @notes.order(:id).each do |note| %>
  <%= sync partial: 'note', resource: note %>
<% end %>

app/views/notes/new.html.erb
<%= render 'form' %>

<div class="center">
	<%= link_to 'Back', notes_path %>
</div>

app/views/notes/show.html.erb
<div class="center">
  <%= sync partial: 'note', resource: @note %>
</div>

app/views/notes/toggle.js.erb
<% if @note.check? %>
  $('#note-label-<%= @note.id %>').css('text-decoration','line-through')
<% else %>
  $('#note-label-<%= @note.id %>').css('text-decoration','none')
<% end %>