config/routes.rb
Pindd::Application.routes.draw do
  resources :groups

  devise_for :users
  resources :notes do
    member do
      put 'toggle'
    end
  end

  root to: 'notes#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :notes, dependent: :destroy

  validates :name, presence: true

  def before_save
    self.email = self.email.downcase
  end

  def member_to_add
  end

  def member_to_remove
  end

  def add_member(user_email = nil)
    if user_email
      user = User.find_by(email: user_email.downcase)
      self.users << user unless self.users.include?(user)
    end
    user ? true : false
  end

  def remove_member(user_email = nil)
    if user_email
      user = User.find_by(email: user_email)
      self.users.delete(user)
    end
    user ? true : false
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  skip_load_resource only: [:create]
  before_action :no_default_access, only: [:show, :edit, :update, :destroy]
  before_action :get_slice_params, only: [:create, :update]
  respond_to :html, :json

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.where(default_group: false).includes(:users).where("users.id" => current_user.id)
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(@group_params)
    @group.default_group = false

    if @group.save
      @group.users << current_user
      process_add_member unless @member_to_add.blank?
      redirect_to @group, notice: 'Group was successfully created.'
      # respond_to do |format|
      #   format.html { redirect_to @group, notice: 'Group was successfully created.' }
      #   format.json { render action: 'show', status: :created, location: @group }
      # end
    else
      render action: 'new'
      # respond_to do |format|
      #   format.html { render action: 'new' }
      #   format.json { render json: @group.errors, status: :unprocessable_entity }
      # end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    process_add_member unless @member_to_add.blank?
    process_remove_member unless @member_to_remove.blank?

    if @group.update(@group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
      # respond_to do |format|
      #   format.html { redirect_to @group, notice: 'Group was successfully updated.' }
      #   format.json { head :no_content }
      # end
    else
      render action: 'edit'
      # respond_to do |format|
      #   format.html { render action: 'edit' }
      #   format.json { render json: @group.errors, status: :unprocessable_entity }
      # end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy unless @group.default_group
    redirect_to groups_url
    # respond_to do |format|
    #   format.html { redirect_to groups_url }
    #   format.json { head :no_content }
    # end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :color, :member_to_add, :member_to_remove)
    end

    def get_slice_params
      @group_params = group_params.slice!(:member_to_add, :member_to_remove)
      @member_to_add = group_params[:member_to_add]
      @member_to_remove = group_params[:member_to_remove]
    end

    def no_default_access
      if @group.default_group?
        redirect_to groups_path
      end
    end

    def process_add_member
      if @group.add_member(@member_to_add)
        flash[:add_member] = @member_to_add + ' was added to group.'
      else
        flash[:add_member_fail] = @member_to_add + ' was not added to group.'
      end
    end

    def process_remove_member
      if @group.remove_member(@member_to_remove)
        flash[:remove_member] = @member_to_remove + ' was removed from group.'
      end
    end
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => 'group-submit' %>
  </div>
  <div class="field">
    <%= f.label :add_member_email %><br>
    <%= f.text_field :member_to_add, :class => 'group-submit' %>
  </div>
  <%= f.select :color, [["Space", "url( #{image_path('space-background.jpg')})"], ["Blue", "#ADC1D6"], ["Pink", "#FA98C4"], ["Green", "#98FABB"], ["Purple", "#D48EF5"], ["Neon Yellow", "#F3F315"], ["Neon Green", "#39FF14"], ["Neon Pink", "#FF0099"], ["Neon Orange", "FF6600"], ["White", "#FFF"]] %>
  <% if @group.users.collect.count > 1 %>
      <div class="field">
        <%= f.label :remove_member %><br>
        <%= f.select :member_to_remove, @group.users.collect { |u| u.email }, :include_blank => true %>
      </div>
  <% end %>
      <div class="actions">
          <%= f.submit :class => 'group-submit' %>
      </div>
<% end %>

app/views/groups/edit.html.erb
<div class="center">
	<div class="new-group">
		<%= render 'form' %>

		<%= link_to 'Show', @group %> |
		<%= link_to 'Back', groups_path %>
	</div>
</div>

app/views/groups/index.html.erb
<div class="lined-paper">
<% @groups.each do |group| %>
    <h2><%= group.name %></h2>
    <div class="group-links">
      <%= link_to 'Show', group %></td>
      <%= link_to 'Edit', edit_group_path(group) %></td>
      <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
<% end %>

 <br>

<div class="btn-group">
  <%= link_to new_group_path, class: 'btn btn-success btn-large' do %>
  <span class="glyphicon glyphicon-plus"></span> New Group
  <% end %>
</div>

app/views/groups/new.html.erb
<div class="center">
	<div class="new-group">
		<h3>New group?</h3>
			<%= render 'form' %>
			<%= link_to 'Back', groups_path %>
	</div>
</div>

app/views/groups/show.html.erb
<div class="show-group">
	<h3>
  		<strong>Group Name:</strong>
  		<br><%= @group.name %>
	</h3>

	<h4>
  		<strong>Group Members:</strong>
  			<ul>
  			<% @group.users.each do |u| %>
    			<li><%= u.email %></li>
  			<% end %>
  			</ul>
	</h4>
	<%= link_to 'Edit', edit_group_path(@group) %> |
	<%= link_to 'Back to Groups', groups_path %>
</div>

<% @group.notes.order(:id).each do |note| %>
  <%= sync partial: 'note', resource: note %>
<% end %>