config/routes.rb
Pindd::Application.routes.draw do
  resources :groups

  devise_for :users
  resources :notes do
    member do
      put 'toggle'
    end
  end

  root to: 'notes#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class= "btn-group btn-group-justified" id="note-nav">
  <div class="btn-group">
    <%= link_to new_note_path, class: 'btn btn-default btn-large' do %>
      <span class="glyphicon glyphicon-pushpin"></span> New Note
    <% end %>
  </div>
  <div class="btn-group">
    <%= link_to groups_path, class: 'btn btn-primary btn large' do %>
      <span class="glyphicon glyphicon-transfer"></span> Groups
    <% end %>
  </div>
  <div class="btn-group">
    <form id="group-form">
    <li class="dropdown">
    <button type= "button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        <span class"sr-only"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <% @user_groups.each do |group| %>
      <li><input id="g_<%= group.id %>" name="groups[]" value="<%= group.id %>" type="checkbox" <%= params[:groups].nil? || params[:groups].include?(group.id.to_s) ? "checked='checked'" : '' %>/><%= link_to group.name, group_path(group) %></li>
      <% end %>
      <li class ="divider"></li>

      <li><%= link_to 'My Notes', root_path %></li>
    </ul>
  </li>
</form>
  </div>
</div>

app/views/layouts/_user.html.erb
<div class="devise-info">
<% if user_signed_in? %>
 	<p>Welcome <%= current_user.email %></p>
    <%= "Logged in!" %>
    <%= link_to raw('<i class="glyphicon glyphicon-cog"></i>'), edit_user_registration_path %>
    <%= link_to '[click to logout]', destroy_user_session_path, :method => :delete %>
<% else %>
    <p>You are not signed in.</p>
    <%= link_to 'Login', new_user_session_path %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PINDD" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PINDD" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <% if Rails.env.development? %>
      <%= javascript_include_tag Sync.adapter_javascript_url %>
    <% end %>
    <%= csrf_meta_tags %>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-47868023-1', 'pindd.herokuapp.com');
      ga('send', 'pageview');
    </script>
    <link href='https://fonts.googleapis.com/css?family=Averia+Sans+Libre|Flamenco' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/user' %>
      <%= render 'layouts/navigation' %>
    <% end %>
    <div class="center">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, msg, class: name %>
      <% end %>
    </div>

    <%= yield %>

  </body>
</html>